#### Today Topics
- Numpy
- Pandas

In [1]:
import numpy as np
ar=np.array([[3,4,5],[1,8,9]])
print(ar)

[[3 4 5]
 [1 8 9]]


In [2]:
#identity,eye() to create identity matrix
1 0 0 
0 1 0
0 0 1

SyntaxError: invalid syntax (1949763783.py, line 2)

In [4]:
print(np.identity(3,dtype=int)) # since square matrix

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
print(np.eye(4,3)) # (row,col)
print(np.identity(5,3)) # unequal size won't work here

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


TypeError: Cannot interpret '3' as a data type

In [12]:
#ones matrix
on=np.ones(5)
o2=np.ones((4,5),dtype=int)
print(on)
print()
print(o2)

[1. 1. 1. 1. 1.]

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [15]:
#zeros matrix
z=np.zeros(10)
print(z)
z2=np.zeros((4,4))
print()
print(z2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
#full and fill
f=np.full(8,'h') # row matrix with 8 h's
f

array(['h', 'h', 'h', 'h', 'h', 'h', 'h', 'h'], dtype='<U1')

In [21]:
f.fill(10) # filled with new data
print(f)

['1' '1' '1' '1' '1' '1' '1' '1']


In [25]:
#diag()
mn=np.arange(25).reshape(5,5)
print(mn) #
print()
print(np.diag(mn)) #getting diagonal elements of the existed array
print()
print(np.diag([5,6,7,8]))#creating the diagonal array with specific values

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[ 0  6 12 18 24]

[[5 0 0 0]
 [0 6 0 0]
 [0 0 7 0]
 [0 0 0 8]]


In [26]:
#linear space()
#linearly separates the given interval
np.linspace(3,7)#50 partitions by default

array([3.        , 3.08163265, 3.16326531, 3.24489796, 3.32653061,
       3.40816327, 3.48979592, 3.57142857, 3.65306122, 3.73469388,
       3.81632653, 3.89795918, 3.97959184, 4.06122449, 4.14285714,
       4.2244898 , 4.30612245, 4.3877551 , 4.46938776, 4.55102041,
       4.63265306, 4.71428571, 4.79591837, 4.87755102, 4.95918367,
       5.04081633, 5.12244898, 5.20408163, 5.28571429, 5.36734694,
       5.44897959, 5.53061224, 5.6122449 , 5.69387755, 5.7755102 ,
       5.85714286, 5.93877551, 6.02040816, 6.10204082, 6.18367347,
       6.26530612, 6.34693878, 6.42857143, 6.51020408, 6.59183673,
       6.67346939, 6.75510204, 6.83673469, 6.91836735, 7.        ])

In [30]:
print(np.linspace(4,5,12).reshape(3,4))#both limits are inclusive

[[4.         4.09090909 4.18181818 4.27272727]
 [4.36363636 4.45454545 4.54545455 4.63636364]
 [4.72727273 4.81818182 4.90909091 5.        ]]


In [29]:
#4,5->2
1/6

0.16666666666666666

#### random()
- random() is the sub module of numpy module
- np.random.randint(up)
    - generates single random digit in a specific range
    - by default the range starts from 0
- np.random.randint(lw,up)
- np.random.randint(lw,up,n)
    - generates n random integeres in a given range
- numpy.random.random(row,col)
    - random samples from 0 to 1(+ve integers) with mentioned size
- numpy.random.rand()
    - this is the short form of random.random()
- numpy.random.randn(row,col)
    - it will generate the -ve random samples 

In [43]:
print(np.random.randint(100))
print(np.random.randint(1000,5000))
print(np.random.randint(100,2000,30).reshape(6,5))

42
2844
[[1109  716 1565  425  849]
 [ 117  212  434 1840  302]
 [1231 1811  811  950 1796]
 [ 548 1182 1412 1720 1341]
 [1630  736  385  785  628]
 [1111 1722 1749 1772  578]]


In [50]:
print(np.random.random((3,4))) # +ve random samples..

[[0.14524312 0.09982229 0.7469519  0.95443809]
 [0.57128964 0.94111251 0.96411668 0.23822198]
 [0.24423687 0.6310574  0.638792   0.26604854]]


In [51]:
print(np.random.rand(3,4))

[[0.94250433 0.13170222 0.71636825 0.99321332]
 [0.12544954 0.59194635 0.05566148 0.57986942]
 [0.40520148 0.93085535 0.14566424 0.86367422]]


In [53]:
print(np.random.randn(3,3)) #-ve random samples

[[-0.08495584  0.97425973  1.4523124 ]
 [ 0.88288609  0.56010701 -0.12873661]
 [-0.76563321 -0.64536283  0.72032479]]


#### accessing the arrays
- using index
- index is of 3types
    1. forward indexing
    2. backward indexing
    3. fancy indexing

In [56]:
rn=np.random.randint(30,500,25).reshape(5,5)
print(rn)

[[243  50 435 485 347]
 [313 168  93 241 181]
 [416 279 341 256 234]
 [414 469 477 274 215]
 [240 182 134 143 491]]


In [57]:
#2d array:array entirely depends upon the row only
rn[0]

array([243,  50, 435, 485, 347])

In [58]:
rn[2]#3rd row sample

array([416, 279, 341, 256, 234])

In [59]:
rn[2:] # contains rows from 3rd

array([[416, 279, 341, 256, 234],
       [414, 469, 477, 274, 215],
       [240, 182, 134, 143, 491]])

In [61]:
print(rn[:])
print()
print(rn[::])

[[243  50 435 485 347]
 [313 168  93 241 181]
 [416 279 341 256 234]
 [414 469 477 274 215]
 [240 182 134 143 491]]

[[243  50 435 485 347]
 [313 168  93 241 181]
 [416 279 341 256 234]
 [414 469 477 274 215]
 [240 182 134 143 491]]


In [65]:
print(rn[::-1]) # represents the array in reverse order
print()
print(rn[::2])#getting alternate rows
print()
print(rn[::-2])#geeting alternate rows in reverse order

[[240 182 134 143 491]
 [414 469 477 274 215]
 [416 279 341 256 234]
 [313 168  93 241 181]
 [243  50 435 485 347]]

[[243  50 435 485 347]
 [416 279 341 256 234]
 [240 182 134 143 491]]

[[240 182 134 143 491]
 [416 279 341 256 234]
 [243  50 435 485 347]]


In [66]:
rn>250# get the original array which satisfy this condition

array([[False, False,  True,  True,  True],
       [ True, False, False, False, False],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True, False],
       [False, False, False, False,  True]])

In [74]:
new=rn[rn>240]#pass the condition as index
print(new)
print("no.of values=",len(new))
print(new.reshape(3,5))

[243 435 485 347 313 241 416 279 341 256 414 469 477 274 491]
no.of values= 15
[[243 435 485 347 313]
 [241 416 279 341 256]
 [414 469 477 274 491]]


In [75]:
#2d indexing
rn[:,2:4]#entire rows,slicing in cols

array([[435, 485],
       [ 93, 241],
       [341, 256],
       [477, 274],
       [134, 143]])

In [76]:
rn[::2,::2]#getting the alternate columns in alternate rows

array([[243, 435, 347],
       [416, 341, 234],
       [240, 134, 491]])

In [77]:
#getting specific value at position
rn[2][3]

256

In [78]:
rn # at 3rd row 4th column

array([[243,  50, 435, 485, 347],
       [313, 168,  93, 241, 181],
       [416, 279, 341, 256, 234],
       [414, 469, 477, 274, 215],
       [240, 182, 134, 143, 491]])

#### scientific computation on the arrays
- mathematical operations
- std,exp,log etc

In [79]:
rn

array([[243,  50, 435, 485, 347],
       [313, 168,  93, 241, 181],
       [416, 279, 341, 256, 234],
       [414, 469, 477, 274, 215],
       [240, 182, 134, 143, 491]])

In [80]:
man=np.arange(25).reshape(5,5)
print(man)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [82]:
#arithmetic operations on both rn & man
print(rn+man)
print()
print(rn-man)
print()
print(rn*man)
print()
print(rn/man)
print()
print(rn//man)
print()
print(rn%man)

[[243  51 437 488 351]
 [318 174 100 249 190]
 [426 290 353 269 248]
 [429 485 494 292 234]
 [260 203 156 166 515]]

[[243  49 433 482 343]
 [308 162  86 233 172]
 [406 268 329 243 220]
 [399 453 460 256 196]
 [220 161 112 120 467]]

[[    0    50   870  1455  1388]
 [ 1565  1008   651  1928  1629]
 [ 4160  3069  4092  3328  3276]
 [ 6210  7504  8109  4932  4085]
 [ 4800  3822  2948  3289 11784]]

[[         inf  50.         217.5        161.66666667  86.75      ]
 [ 62.6         28.          13.28571429  30.125       20.11111111]
 [ 41.6         25.36363636  28.41666667  19.69230769  16.71428571]
 [ 27.6         29.3125      28.05882353  15.22222222  11.31578947]
 [ 12.           8.66666667   6.09090909   6.2173913   20.45833333]]

[[  0  50 217 161  86]
 [ 62  28  13  30  20]
 [ 41  25  28  19  16]
 [ 27  29  28  15  11]
 [ 12   8   6   6  20]]

[[ 0  0  1  2  3]
 [ 3  0  2  1  1]
 [ 6  4  5  9 10]
 [ 9  5  1  4  6]
 [ 0 14  2  5 11]]


C:\Users\sivak\AppData\Local\Temp\ipykernel_33128\2515652672.py:8: RuntimeWarning: divide by zero encountered in true_divide
  print(rn/man)
C:\Users\sivak\AppData\Local\Temp\ipykernel_33128\2515652672.py:10: RuntimeWarning: divide by zero encountered in floor_divide
  print(rn//man)
C:\Users\sivak\AppData\Local\Temp\ipykernel_33128\2515652672.py:12: RuntimeWarning: divide by zero encountered in remainder
  print(rn%man)


In [83]:
#scientific computation
#broad casting(bigger change) with scalar value
print(rn*8) # scalar value applied on vector

[[1944  400 3480 3880 2776]
 [2504 1344  744 1928 1448]
 [3328 2232 2728 2048 1872]
 [3312 3752 3816 2192 1720]
 [1920 1456 1072 1144 3928]]


In [84]:
#logarithms and exponentials
np.log(10)

2.302585092994046

In [85]:
np.log(1)

0.0

In [86]:
np.log(2)

0.6931471805599453

In [87]:
np.log2(2)

1.0

In [88]:
np.log(rn)# finding log values on entire array

array([[5.49306144, 3.91202301, 6.07534603, 6.18414889, 5.84932478],
       [5.74620319, 5.12396398, 4.53259949, 5.48479693, 5.19849703],
       [6.03068526, 5.63121178, 5.83188248, 5.54517744, 5.45532112],
       [6.02586597, 6.15060277, 6.16751649, 5.61312811, 5.37063803],
       [5.48063892, 5.20400669, 4.8978398 , 4.96284463, 6.19644413]])

In [89]:
np.log([4,5,6,10])

array([1.38629436, 1.60943791, 1.79175947, 2.30258509])

In [90]:
rn.std()# standard deviation
# with what differnce of values are getting deviated

126.74594431381227

In [91]:
rn.mean()#average

284.84

In [94]:
print(rn.min())
print(rn.max())
print(rn.sum())

50
491
7121


In [95]:
#exponentials 
np.exp(1)

2.718281828459045

In [96]:
np.exp(rn)

array([[3.41632440e+105, 5.18470553e+021, 8.28132117e+188,
        4.29362116e+210, 5.01401028e+150],
       [8.59355450e+135, 9.15109281e+072, 2.45124554e+040,
        4.62349230e+104, 4.04856601e+078],
       [4.63985567e+180, 1.47285655e+121, 1.24284889e+148,
        1.51142767e+111, 4.21607925e+101],
       [6.27936182e+179, 4.83183408e+203, 1.44034944e+207,
        9.92402938e+118, 2.36218338e+093],
       [1.70088776e+104, 1.10051434e+079, 1.56841351e+058,
        1.27089863e+062, 1.73217041e+213]])

In [97]:
np.exp(2)

7.38905609893065

In [98]:
np.exp(np.log(1))

1.0

In [99]:
np.log(np.exp(2))

2.0

In [105]:
#vectorized functions in numpy
def greater(a,b):
    if a>b:
        return a
    else:return b
    
print(greater(10,4))
print(greater(5,13))
gr=greater([23,4,10],[4,45,3]) # [23,45,10]
print(gr)
g=np.vectorize(greater)
g([23,4,10],[4,45,3])

10
13
[23, 4, 10]


array([23, 45, 10])

#### Pandas
- One of the most efficient modules in data science
- Pandas stands for Panel Data
- the data is arranged in the form of rows columns
- 2 data structures
    1. Series
        - Sequential data is arranged either side by side or line by line
        - pd.Series(data) is the function
        - 1d structure
    2. DataFrame
        - Data can be organized in the form of rows & columns
        - pd.DataFrame(data)
        - 2d strcture
- It is used for data analysis,data manipulation and cleaning
- we will analyse the data,for any further modification and 
- Data Cleaning
    - removes the null values

In [106]:
#apply series on each python iterables/objects
import pandas as pd

In [107]:
st='Ruthu from APSSDC'
print(pd.Series(st)) #a user can see the index values

0    Ruthu from APSSDC
dtype: object


In [110]:
tp=(3,4,5,10,'r',34,'h')
print(pd.Series(tp))

0     3
1     4
2     5
3    10
4     r
5    34
6     h
dtype: object


In [112]:
#example with list
li=['sai tirumala',90,'CSE4',70]
pd.Series(li,index=[3,4,5,6])

3    sai tirumala
4              90
5            CSE4
6              70
dtype: object

In [113]:
#example with set
S={10,34,56,12,9,8} 
pd.Series(S)

TypeError: 'set' type is unordered

In [115]:
S

{8, 9, 10, 12, 34, 56}

In [118]:
roll=[567,452,340]
dic={'clg':'sai tirumala','roll':roll,12:45,'year':4}
pd.Series(dic)#keys will be arranged as index

clg        sai tirumala
roll    [567, 452, 340]
12                   45
year                  4
dtype: object

In [119]:
import numpy as np

In [124]:
first=np.arange(10,34)
pd.Series(first,dtype=complex)

0     10.0+0.0j
1     11.0+0.0j
2     12.0+0.0j
3     13.0+0.0j
4     14.0+0.0j
5     15.0+0.0j
6     16.0+0.0j
7     17.0+0.0j
8     18.0+0.0j
9     19.0+0.0j
10    20.0+0.0j
11    21.0+0.0j
12    22.0+0.0j
13    23.0+0.0j
14    24.0+0.0j
15    25.0+0.0j
16    26.0+0.0j
17    27.0+0.0j
18    28.0+0.0j
19    29.0+0.0j
20    30.0+0.0j
21    31.0+0.0j
22    32.0+0.0j
23    33.0+0.0j
dtype: complex128

In [127]:
#try with random array
rn=np.random.randint(10,700,5)
print(pd.Series(rn,dtype=float,index=[1,2,3,4,5]))

1    504.0
2    329.0
3     59.0
4    226.0
5    229.0
dtype: float64


In [130]:
#date range(year-month-date)
pd.date_range('2022-10-10','2022-10-30')

DatetimeIndex(['2022-10-10', '2022-10-11', '2022-10-12', '2022-10-13',
               '2022-10-14', '2022-10-15', '2022-10-16', '2022-10-17',
               '2022-10-18', '2022-10-19', '2022-10-20', '2022-10-21',
               '2022-10-22', '2022-10-23', '2022-10-24', '2022-10-25',
               '2022-10-26', '2022-10-27', '2022-10-28', '2022-10-29',
               '2022-10-30'],
              dtype='datetime64[ns]', freq='D')

In [132]:
dates=pd.date_range('2023-01-01',periods=10)
pd.Series(dates)

0   2023-01-01
1   2023-01-02
2   2023-01-03
3   2023-01-04
4   2023-01-05
5   2023-01-06
6   2023-01-07
7   2023-01-08
8   2023-01-09
9   2023-01-10
dtype: datetime64[ns]