#### Numpy Module

In [1]:
import numpy as np

arange(),eye,identity(),ones,zeros(),full(),fill(),linspace(),random() etc

In [3]:
ar=np.arange(50).reshape(5,10)
print(ar)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [4]:
#identity matrix
1 0
0 1 
----
1 0 0
0 1 0
0 0 1
-----


SyntaxError: invalid syntax (1886119014.py, line 2)

In [5]:
np.identity(4) # single 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
# ones matrix -->array completed fill with only 1
on=np.ones(4) # row array/matrix
print(on)
print("......")
print(np.ones((3,4),dtype=int))

[1. 1. 1. 1.]
......
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [19]:
#zeros matrix
print(np.zeros(4))
print(np.zeros((4,5),dtype=int))

[0. 0. 0. 0.]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [22]:
#full and fill
fl=np.full(5,'h') # row with 5 h's
print(fl)
f=np.full((5,5),9)
print(f)

['h' 'h' 'h' 'h' 'h']
[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [25]:
# fill (replace the existed matrix)
f.fill(6)
f

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [26]:
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [27]:
np.diag(ar) # you can get the diagonal elements of existed array

array([ 0, 11, 22, 33, 44])

In [28]:
np.diag([4,5,6,9]) # array created with mentioned elements

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 9]])

In [32]:
# linear space(np.linspace(size))
#0 & 1 
np.linspace(2,5) # by default generates 50 samples in the given range

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [35]:
np.linspace(2,20,12) # 12 values(no.of values)
#both limits are inclusive

array([ 2.        ,  3.63636364,  5.27272727,  6.90909091,  8.54545455,
       10.18181818, 11.81818182, 13.45454545, 15.09090909, 16.72727273,
       18.36363636, 20.        ])

#### random()
- this is the sub module of numpy module
- used to generate the random samples and arranged in an array
- random().randint()
- random().randint(,)
- random().randint(,,)
- random().randon()
- random().rand()
- random().randn()

In [46]:
print(np.random.randint(20)) #starts from 0 by default
# any random integer in the given range
print(np.random.randint(30,100))
print(np.random.randint(100,1000,8))

8
84
[726 643 236 477 774 932 604 252]
